package com.deere.global;

public class CommonConstants {
    public static final String LOGIN_PAGE = "Login";
    public static final String MY_JOHN_DEERE_PAGE = "MyJohnDeere";
    public static final String SCHEDULE_PAGE = "Schedule";
    public static final String MY_JOHN_DEERE_LOGIN_PAGE = "MyJohnDeere Login";
    public static final String FORGOT_YOUR_PASSWORD_PAGE = "Forgot your password?";
    public static final String MANAGE_ORDERS_PAGE = "Orders - Manage";
    public static final String UPLOAD_ORDERS_PAGE = "Orders - Upload";
    public static final String ORDER_DETAILS_PAGE = "Order Details";
    public static final String CREATE_ORDER_PAGE = "Create Order";
    public static final String CFF_MANAGE_PAGE = "Customer/Farm/Field - Manage";
    public static final String CFF_UPLOAD_PAGE = "Customer/Farm/Field - Upload";
    public static final String CFF_EDIT_PAGE = "Customer Farm Field - Edit";
    public static final String CFF_DELETE_PAGE = "Delete Clients, Farms, and Fields";
    public static final String EQUIPMENT_MOBILE_DEVICE_PAGE = "Equipment - Mobile Device";
    public static final String EQUIPMENT_UPDATE_MOBILE_DEVICE_PAGE = "Equipment - Update Mobile Device";
    public static final String EQUIPMENT_TENDERS_PAGE = "Equipment -Tenders";
    public static final String EQUIPMENT_APPLICATORS_PAGE = "Equipment -Applicators";
    public static final String EQUIPMENT_CREATE_APPLICATOR_PAGE = "Equipment - CreateApplicator";
    public static final String EQUIPMENT_CREATE_TENDER_PAGE = "Equipment - CreateTender";
    public static final String EQUIPMENT_CREATE_MOBILE_DEVICE_PAGE = "Equipment - Create Mobile Device";
    public static final String EQUIPMENT_UPDATE_APPLICATOR_PAGE = "Equipment - UpdateApplicator";
    public static final String EQUIPMENT_STATUS_PAGE = "Equipment Status";
    public static final String EQUIPMENT_UPDATE_TENDER_PAGE = "Equipment - UpdateTender";
    public static final String FEEDBACK_PAGE = "Feedback";
    public static final String AGLOGIC_HOME_PAGE = "AgLogic - Home";
    public static final String MY_INFO_PAGE = "My Info";
    public static final String ORGANIZATION_PAGE = "Organization";
    public static final String EDIT_ORGANIZATION_PAGE = "Edit Organization";
    public static final String EDIT_PROGRAM_OPTIONS_PAGE = "Edit Program Options";
    public static final String WEB_USERS_PAGE = "Web Users";
    public static final String ADD_EDIT_WEB_USER_PAGE = "Add/Edit Web User";
    public static final String MOBILE_USERS_PAGE = "Mobile Users";
    public static final String ADD_EDIT_MOBILE_USER_PAGE = "Add/Edit Mobile User";
    public static final String LOCATIONS_PAGE = "Locations";
    public static final String ADD_EDIT_LOCATIONS_PAGE = "Add/EditLocation";
    public static final String RECEIVED_MESSAGES_PAGE = "Received Messages";
    public static final String OPERATOR_STATISTICS_PAGE = "Operator Statistics";
    public static final String DELETED_ORDERS_PAGE = "Deleted Orders Report";
    public static final String JOHN_DEERE_US_PAGE = "John Deere US";
    public static final String WHATS_NEW_PAGE = "WHAT'S NEW - VERSION 7.9";
    public static final String FIELD_TICKET_PAGE = "Field Ticket";
    public static final String PRODUCT_TOTAL_PAGE = "Product Total";
    public static final String ASSIGNED_ORDER_SUMMERY_PAGE = "Assigned Order Summery";
    public static final String COMPLETED_ORDERS_PAGE = "Completed Orders";
    public static final String BLEND_SUMMARY_PAGE = "Blend Summary";
    public static final String ASSIGNED_ORDERS_PRODUCT_TOTAL_PAGE = "Assigned Orders - Product Total";
    public static final String FILE_UPLOAD_DIRECTORY = System.getProperty("user.dir") + "//.TestDirectory//";
    public static final String FILE_DOWNLOAD_DIRECTORY = System.getProperty("user.dir") + "//.TestReport//" + "FileDownload//";
    public static final String IMAGE_LOGS_DIRECTORY = System.getProperty("user.dir") + "//.TestReport//" + "ImageLogs//";
    public static final String BROWSER = "Chrome";
    public static final String CERT_URL = "https://aglogicawscert.deere.com/nulog/login.jsp";
    public static final String MOBILE_URL = "https://aglogicawscert.deere.com/nulog/almw/index.htm#login";
    public static final String DEVL_URL = "https://aglogic-devl.deere.com";
    public static final String MYJD_URL = "https://myjohndeerec.deere.com";
    public static final String REGRESSION_SUITE = "RegressionTestData.properties";
    public static final String SMOKE_SUITE = "SmokeTestData.properties";
    public static final String CFF_DELETE_MESSAGE = "Delete was not successful. Field, farm, and client id's are missing.";
    public static final String FILTER_CRITERIA_MESSAGE = "0 Customers match your filter criteria.";
    public static final String UPLOAD_SUCCESS_MESSAGE = "//p[@class='uploadSuccess']";
    public static final String UPLOAD_ERROR_CLASS = "//p[@class='uploadError']";
    public static final String DIAGNOSTIC_DETAILS = ".//*[@id='diagnosticDetails']/table/tbody";
    public static final String APPLICATOR_ORDER_DELETE_MESSAGE = "You cannot delete Applicators that have assigned orders. Please unassign orders from Applicator before deleting.";
    public static final String APPLICATOR_TENDER_DELETE_MESSAGE = "You cannot delete an Applicator that has associated Tenders. Please remove the association before deleting..";
    public static final String UNCHECK_TENDER_LIST = "//table[@class='listTble']/tbody/tr";
    public static final String LICENCE_GROUP = "//*[@id='license']/optgroup[1]";
    public static final String APPLICATOR_COLUMN = "//*[@id='assignOrdersApplicatorList']//tr[1]";
    public static final String FIELD_CONDITION_VALUE = "//input[contains(@name,'fieldConditionValue')]";
    public static final String COLUMN_CONTAIN = ".//*[@id='container']/table/thead/tr/th";
    public static final String ORDER_STATUS = "//td[text()='Order Status']/../td[@id='status1'][text()='Open']";
    public static final String REPORT_HEADER = "(.//*[@class='report-header-text'])";
    public static final String APPLICATOR_REPORT_OPTIONS = "//*[@id='equipmentId']/option";
    public static final String APPLICATOR_HECTARE_RATE = "//*[contains(text(),'Hectare')]";
    public static final String APPLICATOR_ACRE_RATE1 = "//*[contains(text(),'ACRE')]";
    public static final String APPLICATOR_ACRE_RATE2 = "//*[contains(text(),'Acre')]";
    public static final String ATTACHMENT_FILE_INPUT = "//input[@id='attachmentFileInput']";
    public static final String NO_ORDERS_BLOCK = "(//div[contains(@style,'block')]/div[@class='noOrders'])";
    public static final String DISPLAY_ORDERS = "//*[@id='ordersToDisplay']//td[1]";
    public static final String ASSIGNED_ORDER_SELECTOR = "//input[@class='assignedOrderSelector']";
    public static final String NO_TENDER = "//img[@alt='No Tender']";
    public static final String APPLICATOR_LIST = "//td[starts-with(@id,'ValidApp')]";
    public static final String TENDER_LIST = "//td[starts-with(@id,'ValidTender')]";
    public static final String CLIENT_NAME = "//a[contains(@id,'clientName')]";
    public static final String LICENSE_TEXT = ".//*[@id='licenseText'][@disabled]";
    public static final String VALID_NUMBER_ERROR = "Must be a valid Natural number from 1 to 100 minutes.";
    public static final String HYPERLINK = ".//*[@class='hyperLinkDiv']";
    public static final String AGLOGIC_MOBILE_PAGE = "AgLogic Mobile 5.0";
    public static final String ANDROID_APPS_PAGE = "John Deere AgLogicTender – Android Apps on Google Play";
    public static final String TENDER_APPS_PAGE = "John Deere AgLogicTender on the App Store";
    public static final String AGLOGIC_TENDER_PAGE = "John Deere AgLogicTender";
    public static final String NEW_CUSTOMER = "New Customer?";
    public static final String FILTER_CRITERIA = "Displaying [0 to 0] of 0 orders matching your filter criteria.";
}